### ISSUE TITLE
ImageConfigLoader - not correct loading/config of additionalSizes

### ISSUE THREAD

**Issue by HakimFractal** [shopsys/shopsys#1088]
### What is happening
There is a difference between definition of "images.yml" in ``ImageConfigDefinition`` and execution of this config in ``prepareSizes()`` function in ``ImageConfigLoader``. 

I have tried to add "types" into sliderItem config in images.yml - based on example in this file.
```
name: sliderItem
    class: Shopsys\FrameworkBundle\Model\Slider\SliderItem
    types:
        -   name: default
            sizes:
                -   name: ~
                    width: 1232
                    height: 480
                    crop: true
                    occurrence: 'Front-end: Main page slider'
```
This is just a piece of code, that should work. 

But it ends with the error - undefined index additionalSizes:
```$additionalSizes = $this->prepareAdditionalSizes($sizeName ?: '~', $sizeConfig[ImageConfigDefinition::CONFIG_SIZE_ADDITIONAL_SIZES]);```
 If I put it there, it returns - additionalSizes cannot be there. Because the config for sizes under the types do not allow additionalSizes. So it is an endless circle of add -> remove -> add -> remove additional sizes :)
### Expected result

Config file or loading function should be modified. For now, "type" functionality in images cannot be used.
