### ISSUE TITLE
Skip rules for ECS should be limited to specific package when run from monorepo

### ISSUE THREAD

**Issue by grossmannmartin** [shopsys/shopsys#1249]
### What is happening
Currently, from a monorepo root we have `easy-coding-standard.yml` file in which are imported configurations from all packages
```yml
imports:
    - { resource: 'packages/coding-standards/easy-coding-standard.yml' }
    - { resource: 'packages/*/easy-coding-standard.yml' }
    - { resource: 'project-base/easy-coding-standard.yml' }
```

When we add a `skip` parameter related only for one package, 
running ECS from monorepo will skip this rule for the whole codebase. That hides coding-standards violations that should be reported and furthermore when the monorepo is split, Travis checks packages one by one and finds errors.

In addition when we need differently configured checks for every package we have to think about naming those services differently.
Example of this issue is `Shopsys\CodingStandards\CsFixer\ForbiddenPrivateVisibilityFixer` which needs to be configured like 
```yml
 this package is meant to be extensible using class inheritance, so we want to avoid private visibilities in these namespaces
    forbidden_private_visibility_fixer.framework:
        class: Shopsys\CodingStandards\CsFixer\ForbiddenPrivateVisibilityFixer
        calls:
            - method: configure
              arguments:
                - analyzed_namespaces:
                    - Shopsys\FrameworkBundle\Model
                    - Shopsys\FrameworkBundle\Component
                    - Shopsys\FrameworkBundle\Controller
                    - Shopsys\FrameworkBundle\Twig
```
in framework and with different name in other package:
```yml
   forbidden_private_visibility_fixer.product_feed_google:
        class: Shopsys\CodingStandards\CsFixer\ForbiddenPrivateVisibilityFixer
        calls:
            - method: configure
              arguments:
                  - analyzed_namespaces:
                        - Shopsys\ProductFeed\GoogleBundle\Model
```

### Expected result

ECS configurations should be independent on each other when running from monorepo.
