### ISSUE TITLE
Build application in kubernetes should be simplified

### ISSUE THREAD

**Issue by grossmannmartin** [shopsys/shopsys#1271]
### What is happening
In deploy/build scripts is often used yq to replace placeholders or some values with the proper one right for the environment.

This replacement often looks like 
```sh
# Set environment variables to container and initContainer for Google Cloud Storage connection - set it to null
yq write --inplace project-base/kubernetes/deployments/webserver-php-fpm.yml spec.template.spec.containers[0].env[0].value 'bucket-name'
yq write --inplace project-base/kubernetes/deployments/webserver-php-fpm.yml spec.template.spec.containers[0].env[1].value 'project-id'
yq write --inplace project-base/kubernetes/deployments/webserver-php-fpm.yml spec.template.spec.initContainers[1].env[0].value 'bucket-name'
yq write --inplace project-base/kubernetes/deployments/webserver-php-fpm.yml spec.template.spec.initContainers[1].env[1].value 'project-id'
```

Which transforms (shortened example)

```yaml
spec:
    template:
            initContainers:
                -   name: copy-source-codes-to-volume
                -   name: initialize-database
                    env:
                        -   name: GOOGLE_CLOUD_STORAGE_BUCKET_NAME
                            value: ~
                        -   name: GOOGLE_CLOUD_PROJECT_ID
                            value: ~
            containers:
                -   name: php-fpm
                    env:
                        -   name: GOOGLE_CLOUD_STORAGE_BUCKET_NAME
                            value: ~
                        -   name: GOOGLE_CLOUD_PROJECT_ID
                            value: ~
```

into

```yaml
spec:
    template:
            initContainers:
                -   name: copy-source-codes-to-volume
                -   name: initialize-database
                    env:
                        -   name: GOOGLE_CLOUD_STORAGE_BUCKET_NAME
                            value: bucket-name
                        -   name: GOOGLE_CLOUD_PROJECT_ID
                            value: project-id
            containers:
                -   name: php-fpm
                    env:
                        -   name: GOOGLE_CLOUD_STORAGE_BUCKET_NAME
                            value: bucket-name
                        -   name: GOOGLE_CLOUD_PROJECT_ID
                            value: project-id
```

This is violation of DRY and most of all very fragile solution.
It's really easy to prepend new env variable as the @PetrHeinz correctly pointed out.

Maybe we could use Kustomize variables (see [vars documentation](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/fields.md#vars) or [an example using vars](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/wordpress/README.md)) to not repeat ourselves like this.

### Expected result

Scripts should be less error-prone and simplified.
