### ISSUE TITLE
How to check data in Elasticsearch?

### ISSUE THREAD

**Issue by pk16011990** [shopsys/shopsys#1288]
### What is happening
SSFW devstack contains the Adminer, Redis Admin, but nothing for Elasticsearch. Documentation contains only note like `you can use Kibana or Postman` that's all... In my point of view, it is uncompleted for development. I don't have any tool for working locally with Elasticsearch installed. 

### Expected results
Development devstack contains some GUI for Elasticsearch - Kibana or something like that or documentation tells us how to install it easily. I used
```bash
$ docker run --name kibana -p 5601:5601 --link "shopsys-framework-elasticsearch:elasticsearch_alias" --network="shopsys_default" -e "ELASTICSEARCH_URL=http://elasticsearch_alias:9200" docker.elastic.co/kibana/kibana-oss:6.3.2
```

or extend `docker-compose.yml`:
```yaml
kibana:
        image: docker.elastic.co/kibana/kibana-oss:6.3.2
        container_name: shopsys-framework-kibana
        links:
            - elasticsearch
        environment:
            - ELASTICSEARCH_USERNAME=kibana
            - ELASTICSEARCH_PASSWORD=root
        ports:
            - "5601:5601"
```
