### ISSUE TITLE
Authenticator should not be dependent on `TraceableEventDispatcher`

### ISSUE THREAD

**Issue by grossmannmartin** [shopsys/shopsys#1597]
### What is happening

`Shopsys\FrameworkBundle\Model\Security\Authenticator` class is dependent on `Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher`, which is according to [documentation](https://symfony.com/doc/current/components/event_dispatcher/traceable_dispatcher.html) more a development thing (TraceableEventDispatcher needs a `symfony/stopwatch` which is in dev-requirements only) 

We use this dispatcher directly in Authenticator class

```yaml
Shopsys\FrameworkBundle\Model\Security\Authenticator:
    arguments:
        - '@security.token_storage'
        - '@Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher'

Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher:
    arguments:
        - '@event_dispatcher'
```

EventDispatcher class should be sufficient for production use. 

### Expected result

The authenticator class is rewritten, or reasons are documented.
