### ISSUE TITLE
Creating a Multidomain Design is not possible

### ISSUE THREAD

**Issue by grossmannmartin** [shopsys/shopsys#2042]
### What is happening
Templates can no longer be overriden for specific domain as described in cookbook https://docs.shopsys.com/en/9.0/cookbook/creating-a-multidomain-design/#scenario-2-i-want-to-change-layout-in-footer-on-my-2nd-domain

Class responsible for loading multidomain templates (`Shopsys\FrameworkBundle\Component\Domain\Multidomain\Twig\FilesystemLoader`) seems unused and service definition does not feel right as constructor of the class accepts only two arguments 

```yaml
twig.loader.filesystem:
        class: Shopsys\FrameworkBundle\Component\Domain\Multidomain\Twig\FilesystemLoader
        arguments:
            $locator: '@templating.locator'
            $parser: '@templating.name_parser'
            $rootPath: '%kernel.project_dir%'
            $domain: '@Shopsys\FrameworkBundle\Component\Domain\Domain'
```

It seems that in container is the loader registered with different id (`twig.loader.native_filesystem`)

### Expected result

I can follow cookbook to create a multidomain templates.
Test for this multidomain template feature exists.
