### ISSUE TITLE
Improving introduction to FE API

### ISSUE THREAD

**Issue by malyMiso** [shopsys/shopsys#2168]
## Describe the expected outcome of your requested feature
There are few unexpected situations in FE API, I was not prepared for, after reading [Introduction to FE API](https://docs.shopsys.com/en/9.0/frontend-api/introduction-to-frontend-api/). I would like to update it, so others will know how to deal with it.
#### Extensibility of the API
There is an info how to extend type `Category`. It works as is described in documentation. However I added new field `weight` to entity `Product`, then I defined new field in `Product.types.yaml`, which is an interface:
```
Product:
    type: interface
    inherits:
        - 'ProductDecorator'
    config:
        fields:
            weight:
                type: "String"
                description: "weight in kg"
```

`Product.weight` is exported to Elastic. I had to extend `ProductResolverMap` because of handling data from Elastic. It took me a while **to understand why and how**. It would be nice to have that info in section `Resolver Maps` or somewhere else. Something like, if you export field of entity (e.g. `Product`) to Elastic, you shall resolve this field by your own, using resolver map.

I assume, that example with product will be sufficient.

After extending `ProductResolverMap` I thought I am ready, so I ran some queries. Queries failed, because newly defined field `weight` was unknown for `RegularProduct`, `MainVariant`, `Variant`. I solved it by copying field definition to the rest types. 
What is the best way to extend `Product` type ?

#### Resolvers
First sentence in documentation says `Resolvers are normal Symfony services`, which IMHO could be misleading. I extended `ImagesResolver`, because I wanted to add new resolver for entity (e.g `Country`). I extended it the same way I extend other SSFW services:
```
    Shopsys\FrontendApiBundle\Model\Resolver\Image\ImagesResolver:
        alias: App\Model\Resolver\Image\ImagesResolver
```
After that, Image resolvers from namespace `Shopsys\FrontendApiBundle\Model\Resolver\Image` can't be found. It is because of using fully qualified class namespace in graphql types definition e.g. 
```
            images:
                type: "[Image]!"
                description: "Brand images"
                resolve: '@=service("Shopsys\\FrontendApiBundle\\Model\\Resolver\\Image\\ImagesResolver").resolveByBrand(value, args["type"], args["size"])'
                args:
                    type:
                        type: "String"
                        defaultValue: null
                    size:
                        type: "String"
```

I tried to create `ImagesResolverInterface` as service in SSFW directly (I would be able to make PR, if it worked), but it didn't work. I tried to defined resolvers by aliases, but it didn't work either.
I will be grateful, if there is some way how to override these services the standard way. Maybe I am missing something.

For now I do not recommend to extend resolvers the standard Symfony way. Otherwise you should rewrite all fields using extended service and change FQCN. 
I think, that such an info can be helpful for other programmers and save their time.

Guys, do you think, that upgrading documentation, will be sufficient to deal with described scenarios ? For now, I do not know better way. 

### Additional context
Feel free to contact me and we can discuss it in more detail
