### ISSUE TITLE
annotation fixer ignores services extended with `class` keyword

### ISSUE THREAD

**Issue by grossmannmartin** [shopsys/shopsys#2539]
## Describe the bug
When service is extended with the `class` keyword (for example when tagging is needed) 

```yaml
    Shopsys\FrameworkBundle\Model\Product\ProductVisibilityFacade:
        class: App\Model\Product\ProductVisibilityFacade
        tags:
            # must be ran after CategoryVisibilityRepository and ProductPriceRecalculator
            - {
                name: kernel.event_listener,
                event: kernel.response,
                method: onKernelResponse,
                priority: 10,
                }
```

Annotation fixer do not change annotations at all.  

When `alias` is used

```yaml
    Shopsys\FrameworkBundle\Model\Product\ProductVisibilityFacade:
        alias: App\Model\Product\ProductVisibilityFacade
```

Everything work as expected.

### Expected behavior
Annotations for services extended with `class` keyword are replaced the same way as they are with `alias`, or the behavior is documented, if it's intentional.
