### ISSUE TITLE
Problems with sf15 project installation 

### ISSUE THREAD

**Issue by hauso** [shopsys/shopsys#3528]
Win 11 + docker desktop

1.  **OPTIONAL** missing dir name in composer craete project
  composer create_project shopsys/project-base --no-install --keep-vcs --ignore-platform-reqs
    replace with
  composer create_project shopsys/project-base PROJECT_DIR --no-install --keep-vcs --ignore-platform-reqs

2. problem with running install script 
   _#./scripts/install.sh_ returns
   -bash: ./scripts/install.sh: /bin/bash^M: bad interpreter: No such file or directory
     problem is in CRLF line ends, solution:
```
   sed -i -e 's/\r$//' scripts/install.sh
   sed -i -e 's/\r$//' scripts/configure.sh
```
   
3. storefront container crash 
  error message:  exec /entrypoint.sh: no such file or directory
    solution:
   from _storefront/docker/dev.Dockerfile_ remove
```
    COPY docker/entrypoint.sh /
    ENTRYPOINT ["/entrypoint.sh"]
```
    
and instead update storefront container definition in _docker/conf/docker-compose.yml.dist_

```
storefront:
        restart: always
        build:
            context: ./storefront
            dockerfile: ./docker/dev.Dockerfile
            target: development
            args:
                node_uid: 1000
        container_name: shopsys-framework-storefront
        command: # Optional
            - dev # change to `- build` if you want to test application build
        volumes:
            - ./storefront:/home/node/app
        entrypoint:
            - /bin/sh
            - /home/node/app/docker/entrypoint.sh
        ports:
            - "3000:3000"
```
