### ISSUE TITLE
Do not use link and depends_on in docker-compose files

### ISSUE THREAD

**Issue by MattCzerner** [shopsys/shopsys#505]
### What is happening
In `docker-compose.yml` we use `links` and `depends_on` and im not sure for what.

If i just delete these parameters, everything works well.

### Expected result
Do not use unnecessary parameters in docker-compose.yml

**Comment by PetrHeinz** [comment]
I would remove [links](https://docs.docker.com/compose/compose-file/#links) as it's a legacy feature and we probably don't even use it properly...

I would leave [depends_on](https://docs.docker.com/compose/compose-file/#depends_on) included, as it describes the order of containers to be started (eg. start the microservices before `php-fpm` is started), which makes sense imo.

**Comment by PetrHeinz** [comment]
One reason that I provided is that it forces the microservices to start before `php-fpm` is started. As can be seen here https://github.com/shopsys/shopsys/blob/master/docker/conf/docker-compose.yml.dist, `php-fpm` container is dependend on the microservices.

The Heimdall build you provided is not much of an argument, as it doesn't use Docker Composer to start the containers. I do believe it works though (I've tested it locally), and I wouldn't mind removing it altogether in the sake of simplicity.

Personally, I am against any reordering of the configuration until we have some process in place, that will check the order or force it in any way. Imo, the best way to go is to sort the services alphabetically, as proposed in #199 (it would have to be extended to include `*.yml.dist` files as well).

**Comment by MattCzerner** [comment]
No its not:
```
 php-fpm:
        build:
            context: project-base/docker/php-fpm
            args: &common_build_args
                www_data_uid: 1000
                www_data_gid: 1000
                github_oauth_token: place-your-token-here
        container_name: shopsys-framework-php-fpm
        volumes:
            - .:/var/www/html
        links:
            - microservice-product-search
            - microservice-product-search-export
            - postgres
            - redis
        ports:
            - "35729:35729"
        depends_on:
            - postgres
            - redis
```

It is just linked to them, not dependent.

Okay i agree with the reordering that it does not make sense without some sniff or something. 

I keep PR for deleteing links and depends_on same as it was. And will inform @LukasHeinz that it can be added to sprint for CR
