### ISSUE TITLE
Run shopsys/shopsys in docker Windows 10 pro - permission denied

### ISSUE THREAD

**Issue by sspooky13** [shopsys/shopsys#713]
Hello, it's maybe problem in my pc but i can't run docker-compose for microservice. Can you help me with this?
Thanks.

### What is happening
I make all points from article https://github.com/shopsys/shopsys/blob/master/docs/installation/installation-using-docker-windows-10-pro-higher.md at least 5 times but i can't run microservice for shopsys/shopsys repository. I try run shopsys/project-base from guide and it's working.
When i try run `docker-compose up -d` twice in shopsys/project-base repository it's work all fine:
```bash
peter@Peter:/c/Users/Peter/Documents/project-base$ docker-compose up -d
Creating network "project-base_default" with the default driver
Creating shopsys-framework-postgres                           ... done
Creating shopsys-framework-redis-admin                        ... done
Creating shopsys-framework-php-fpm                            ... done
Creating shopsys-framework-microservice-product-search        ... done
Creating shopsys-framework-redis                       ...
Creating shopsys-framework-redis                              ... done
Creating shopsys-framework-smtp-server                        ... done
Creating shopsys-framework-adminer                            ... done
Creating shopsys-framework-acceptance-tests                   ... done
Creating shopsys-framework-elasticsearch                      ... done
Creating shopsys-framework-webserver                          ... done
WARNING: Connection pool is full, discarding connection: 127.0.0.1
peter@Peter:/c/Users/Peter/Documents/project-base$ docker-compose up -d
shopsys-framework-postgres is up-to-date
shopsys-framework-redis-admin is up-to-date
shopsys-framework-microservice-product-search is up-to-date
shopsys-framework-webserver is up-to-date
shopsys-framework-elasticsearch is up-to-date
shopsys-framework-microservice-product-search-export is up-to-date
shopsys-framework-acceptance-tests is up-to-date
shopsys-framework-adminer is up-to-date
shopsys-framework-php-fpm is up-to-date
shopsys-framework-redis is up-to-date
shopsys-framework-smtp-server is up-to-date
```
but if i try run `docker-compose up -d` twice in shopsys/shopsys repository, then show me:
```bash
peter@Peter:/c/html/shopsys$ docker-compose up -d
Creating network "shopsys_default" with the default driver
Creating shopsys-framework-microservice-product-search        ... done
Creating shopsys-framework-smtp-server                        ... done
Creating shopsys-framework-microservice-product-search-export ... done
Creating shopsys-framework-adminer                            ... done
Creating shopsys-framework-acceptance-tests                   ... done
Creating shopsys-framework-redis                              ... done
Creating shopsys-framework-php-fpm                            ... done
Creating shopsys-framework-redis-admin                        ... done
Creating shopsys-framework-postgres                           ... done
Creating shopsys-framework-elasticsearch                      ... done
Creating shopsys-framework-webserver                          ... done
peter@Peter:/c/html/shopsys$ docker-compose up -d
shopsys-framework-redis-admin is up-to-date
shopsys-framework-redis is up-to-date
shopsys-framework-elasticsearch is up-to-date
shopsys-framework-postgres is up-to-date
Starting shopsys-framework-microservice-product-search-export ...
shopsys-framework-php-fpm is up-to-date
Starting shopsys-framework-microservice-product-search        ...
shopsys-framework-adminer is up-to-date
shopsys-framework-smtp-server is up-to-date
Starting shopsys-framework-microservice-product-search-export ... done
Starting shopsys-framework-microservice-product-search        ... done
```
If i try run `docker-compose up` (i don't know what `-d` doing) then show me:
```bash
shopsys-framework-microservice-product-search | standard_init_linux.go:190: exec user process caused "permission denied"
shopsys-framework-adminer             | PHP 7.2.12 Development Server started at Sun Jan  6 09:54:02 2019
shopsys-framework-smtp-server         | + sed -ri '
shopsys-framework-smtp-server         |         s/^#?(dc_local_interfaces)=.*/\1='\''[0.0.0.0]:25 ; [::0]:25'\''/;
shopsys-framework-smtp-server         |         s/^#?(dc_other_hostnames)=.*/\1='\'''\''/;
shopsys-framework-smtp-server         |         s/^#?(dc_relay_nets)=.*/\1='\''172.24.0.3\/16'\''/;
shopsys-framework-smtp-server         |         s/^#?(dc_eximconfig_configtype)=.*/\1='\''internet'\''/;
shopsys-framework-smtp-server         | ' /etc/exim4/update-exim4.conf.conf
shopsys-framework-smtp-server         | + update-exim4.conf -v
shopsys-framework-smtp-server         | using non-split configuration scheme from /etc/exim4/exim4.conf.template
shopsys-framework-smtp-server         |     1 LOG: MAIN
shopsys-framework-smtp-server         |     1   exim 4.84_2 daemon started: pid=1, -q15m, listening for SMTP on port 25 (IPv6 and IPv4)
shopsys-framework-microservice-product-search-export | standard_init_linux.go:190: exec user process caused "permission denied"
...
...
...
shopsys-framework-php-fpm             | [06-Jan-2019 09:54:04] NOTICE: ready to handle connections
shopsys-framework-microservice-product-search exited with code 1
shopsys-framework-microservice-product-search-export exited with code 1
```
I try clone `shopsys/shopsys` repository into document folder but result is same.

### Expected result
`docker-compose up -d` in windows 10 pro run correctly.

**Comment by MattCzerner** [comment]
Hi @sspooky13,
after running `docker-compose up -d` for a first time, run `docker ps` which lists all running containers, my guess is that microservices will not be in the list.

That means that microservices werent started correctly, thankfully, you can run `docker logs shopsys-framework-microservice-product-search` and `docker logs shopsys-framework-microservice-product-search-export` which will outputs you error on which microservices have failed. Can you send the output of docker logs here, so I can help you


Also, you were asking about what `-d` means, its a `detach mode` which means that docker starts containers in background and only outputs names of containers, without `-d` it outputs log from container start.

**Comment by vitek-rostislav** [comment]
Hi @sspooky13, could you please paste here the content of your `docker-compose.yml`?

There are different templates for monorepo and `project-base` and installation guides are referring to the ones in `project-base`. The difference is mentioned in https://github.com/shopsys/shopsys/blob/master/docs/introduction/monorepo.md#installation-of-monorepo.

By any chance you have used the `project-base/docker/conf/docker-compose-win.yml.dist` instead of `docker/conf/docker-compose-win.yml.dist` :question: 

The same apllies to `docker-sync-win.yml.dist` template.

Btw
> (i don't know what -d doing)

It is just an option to run the containers in the background so your terminal is not blocked by the process :slightly_smiling_face:

**Comment by sspooky13** [comment]
Hi guys, thanks for your help, i appreciate it and thanks for explanation `-d` parameters 🙂.

@MattCzerner, after run `docker-compose up -d`, i run `docker ps` but as you say, that services are not in the lists. Here is the list:
```bash
peter@Peter:/c/html/shopsys$ docker ps
CONTAINER ID        IMAGE                                                     COMMAND                  CREATED             STATUS              PORTS                                NAMES
598534a31801        nginx:1.13-alpine                                         "nginx -g 'daemon of…"   15 seconds ago      Up 11 seconds       80/tcp, 0.0.0.0:8000->8080/tcp       shopsys-framework-webserver
7c436c525f45        postgres:10.5-alpine                                      "docker-entrypoint.s…"   21 seconds ago      Up 11 seconds       5432/tcp                             shopsys-framework-postgres
9ec7bc01b7bb        namshi/smtp:latest                                        "/bin/entrypoint.sh …"   21 seconds ago      Up 13 seconds       25/tcp                               shopsys-framework-smtp-server
0f7317a20cf4        shopsys_php-fpm                                           "docker-php-entrypoi…"   21 seconds ago      Up 15 seconds       9000/tcp, 0.0.0.0:35729->35729/tcp   shopsys-framework-php-fpm
f82618f07b31        docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.2   "/usr/local/bin/dock…"   21 seconds ago      Up 15 seconds       0.0.0.0:9200->9200/tcp, 9300/tcp     shopsys-framework-elasticsearch
c9e89fce7c88        redis:4.0-alpine                                          "docker-entrypoint.s…"   21 seconds ago      Up 14 seconds       6379/tcp                             shopsys-framework-redis
1e78a0481788        adminer:4.6                                               "entrypoint.sh docke…"   21 seconds ago      Up 12 seconds       0.0.0.0:1100->8080/tcp               shopsys-framework-adminer
ff7f9d9f917d        erikdubbelboer/phpredisadmin:v1.10.2                      "php -S 0.0.0.0:80"      21 seconds ago      Up 18 seconds       0.0.0.0:1600->80/tcp                 shopsys-framework-redis-admin
d60f29ac916f        selenium/standalone-chrome:3.11                           "/opt/bin/entry_poin…"   21 seconds ago      Up 14 seconds       0.0.0.0:4400->4444/tcp               shopsys-framework-acceptance-tests
c132ef5a5149        eugenmayer/unison:2.51.2.1                                "/entrypoint.sh supe…"   2 minutes ago       Up 2 minutes        127.0.0.1:32777->5000/tcp            shopsys-framework-vendor-sync
7c081d5bac4c        eugenmayer/unison:2.51.2.1                                "/entrypoint.sh supe…"   2 minutes ago       Up 2 minutes        127.0.0.1:32776->5000/tcp            shopsys-framework-web-sync
9d3862cd4bfe        eugenmayer/unison:2.51.2.1                                "/entrypoint.sh supe…"   2 minutes ago       Up 2 minutes        127.0.0.1:32775->5000/tcp            shopsys-framework-microservice-product-search-export-sync
b66f2a63be2f        eugenmayer/unison:2.51.2.1                                "/entrypoint.sh supe…"   2 minutes ago       Up 2 minutes        127.0.0.1:32774->5000/tcp            shopsys-framework-microservice-product-search-sync
966c1a27e191        eugenmayer/unison:2.51.2.1                                "/entrypoint.sh supe…"   3 minutes ago       Up 3 minutes        127.0.0.1:32773->5000/tcp            shopsys-framework-sync
```
Unfortunately, logs have zero informations ☹. I run 2 commands as you said: `docker logs shopsys-framework-microservice-product-search` and `docker logs shopsys-framework-microservice-product-search-export` but they have only this informations:
```bash
peter@Peter:/c/html/shopsys$ docker logs shopsys-framework-microservice-product-search
standard_init_linux.go:190: exec user process caused "permission denied"
peter@Peter:/c/html/shopsys$ docker logs shopsys-framework-microservice-product-search-export
standard_init_linux.go:190: exec user process caused "permission denied"
```


@vitek-rostislav, sure. I paste here `docker-compose.yml` and `docker-sync.yml` for sure.
### docker-compose.yml
```yaml
version: "3.4"

x-variables:
    common_build_args: &common_build_args
        www_data_uid: 1000
        www_data_gid: 1000

services:
    postgres:
        image: postgres:10.5-alpine
        container_name: shopsys-framework-postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./project-base/docker/postgres/postgres.conf:/var/lib/postgresql/data/postgresql.conf
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=shopsys

    webserver:
        image: nginx:1.13-alpine
        container_name: shopsys-framework-webserver
        depends_on:
            - php-fpm
        volumes:
            - shopsys-framework-web-sync:/var/www/html/project-base/web
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8000:8080"

    php-fpm:
        build:
            context: .
            dockerfile: project-base/docker/php-fpm/Dockerfile
            target: development
            args:
                <<: *common_build_args
                project_root: project-base
        container_name: shopsys-framework-php-fpm
        volumes:
            - shopsys-framework-sync:/var/www/html
            - shopsys-framework-vendor-sync:/var/www/html/vendor
            - shopsys-framework-web-sync:/var/www/html/web
            - ./project-base/docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/php.ini
        ports:
            - "35729:35729"

    microservice-product-search:
        build:
            context: microservices/product-search
            dockerfile: docker/Dockerfile
            target: development
            args:
                <<: *common_build_args
        container_name: shopsys-framework-microservice-product-search
        volumes:
            - ./microservices/product-search:/var/www/html

    microservice-product-search-export:
        build:
            context: microservices/product-search-export
            dockerfile: docker/Dockerfile
            target: development
            args:
                <<: *common_build_args
        container_name: shopsys-framework-microservice-product-search-export
        volumes:
            - ./microservices/product-search-export:/var/www/html

    redis:
        image: redis:4.0-alpine
        container_name: shopsys-framework-redis

    redis-admin:
        image: erikdubbelboer/phpredisadmin:v1.10.2
        container_name: shopsys-framework-redis-admin
        environment:
            - REDIS_1_HOST=redis
        ports:
            - "1600:80"

    selenium-server:
        image: selenium/standalone-chrome:3.11
        container_name: shopsys-framework-acceptance-tests
        ports:
            - "4400:4444"
        environment:
            - HUB_PORT_4444_TCP_ADDR=hub
            - HUB_PORT_4444_TCP_PORT=4444

    adminer:
        image: adminer:4.6
        container_name: shopsys-framework-adminer
        ports:
            - "1100:8080"

    smtp-server:
        image: namshi/smtp:latest
        container_name: shopsys-framework-smtp-server

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.2
        container_name: shopsys-framework-elasticsearch
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        ports:
            - "9200:9200"
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        environment:
            - discovery.type=single-node

volumes:
    pgdata:
        driver: local
    elasticsearch-data:
        driver: local
    shopsys-framework-sync:
        external: true
    shopsys-framework-vendor-sync:
        external: true
    shopsys-framework-web-sync:
        external: true
```
### docker-sync.yml
```yaml
version: '2'
syncs:
    shopsys-framework-sync:
        sync_userid: 1000
        sync_host_port: 10872
        sync_strategy: 'unison'
        src: './'
        sync_excludes: [
            '.ci',
            '.git',
            '.github',
            '.idea',
            '.docker-sync',
            '.DS_Store',
            'docker',
            'nbproject',
            'project-base/docker',
            'project-base/docs',
            'project-base/kubernetes',
            'project-base/node_modules',
            'project-base/var/cache',
            'project-base/var/elasticsearch-data',
            'project-base/var/postgres-data',
            'project-base/web',
            'vendor'
        ]
        host_disk_mount_mode: 'delegated'

    shopsys-framework-microservice-product-search-sync:
        sync_userid: 1000
        sync_strategy: 'unison'
        src: './microservices/product-search/'

    shopsys-framework-microservice-product-search-export-sync:
        sync_userid: 1000
        sync_strategy: 'unison'
        src: './microservices/product-search-export/'

    shopsys-framework-web-sync:
        sync_userid: 1000
        sync_strategy: 'unison'
        src: './project-base/web'
        host_disk_mount_mode: 'cached'

    shopsys-framework-vendor-sync:
        sync_userid: 1000
        sync_strategy: 'unison'
        src: './vendor'
        host_disk_mount_mode: 'cached'
```
I read the article about monorepo but i think, i have all point correctly done. On 99% i used `docker/conf/docker-compose-win.yml.dist`, because you can see in `docker-compose.yml` file, my services looks this:
```yaml
microservice-product-search:
        build:
            context: microservices/product-search
            dockerfile: docker/Dockerfile
            target: development
            args:
                <<: *common_build_args
        container_name: shopsys-framework-microservice-product-search
        volumes:
            - ./microservices/product-search:/var/www/html

    microservice-product-search-export:
        build:
            context: microservices/product-search-export
            dockerfile: docker/Dockerfile
            target: development
            args:
                <<: *common_build_args
        container_name: shopsys-framework-microservice-product-search-export
        volumes:
            - ./microservices/product-search-export:/var/www/html
```
and `project-base/docker/conf/docker-compose-win.yml.dist` microservices looks this:
```yaml
    microservice-product-search:
        image: shopsys/microservice-product-search:latest
        container_name: shopsys-framework-microservice-product-search

    microservice-product-search-export:
        image: shopsys/microservice-product-search-export:latest
        container_name: shopsys-framework-microservice-product-search-export
```

**Comment by sspooky13** [comment]
@boris-brtan, no i don't clone shopsys/shopsys via WSL because shopsys/shopsys repository is not in packagist and i don't know how to clone this repo from github. 
I found some command in google but it's not working
```bash
peter@Peter:/c/html$ composer create-project shopsys/shopsys --stability=beta --no-install --keep-vcs --repository-url=https://github.com/shopsys/shopsys.git


  [Composer\Downloader\TransportException]
  The "https://github.com/shopsys/shopsys.git/packages.json" file could not be downloaded (HTTP/1.1 404 Not Found)
```
```bash
peter@Peter:/c/html$ composer create-project shopsys/shopsys --stability=beta --no-install --keep-vcs --repository-url=http://github.com/shopsys/shopsys.git


  [Composer\Downloader\TransportException]
  Your configuration does not allow connections to http://github.com/shopsys/shopsys.git/packages.json. See https://g
  etcomposer.org/doc/06-config.md#secure-http for details.
```
I will be glad for every help to clone this repo via WSL.
I am not a linux user but i think i am owner but judge yourself
```bash
peter@Peter:/c/html/shopsys$ id
uid=1000(peter) gid=1000(peter) groups=1000(peter),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),999(docker)
peter@Peter:/c/html/shopsys$ ls -la
total 540
drwxr-xr-x 1 peter peter    512 Jan 10 19:42 .
drwxr-xr-x 1 peter peter    512 Jan 10 19:40 ..
-rwxr--r-- 1 peter peter     19 Jan  6 10:16 bin
-rwxr--r-- 1 peter peter  14898 Jan  6 10:16 build.xml
-rwxr--r-- 1 peter peter   2770 Jan  6 10:16 changelog-linker.yml
-rwxr--r-- 1 peter peter 103458 Jan  6 10:16 CHANGELOG.md
drwxr-xr-x 1 peter peter    512 Jan  6 10:16 .ci
-rwxr--r-- 1 peter peter   7406 Jan  6 10:16 composer.json
-rwxr--r-- 1 peter peter 365367 Jan  6 10:20 composer.lock
-rwxr--r-- 1 peter peter   1885 Jan  6 10:16 CONTRIBUTING.md
drwxr-xr-x 1 peter peter    512 Jan  6 10:16 docker
-rwxr--r-- 1 peter peter   3824 Jan  6 10:20 docker-compose.yml
-rwxr--r-- 1 peter peter    718 Jan  6 10:16 .dockerignore
-rwxr--r-- 1 peter peter   1409 Jan  6 10:20 docker-sync.yml
drwxr-xr-x 1 peter peter    512 Jan  8 22:52 docs
-rwxr--r-- 1 peter peter    200 Jan  6 10:16 easy-coding-standard.yml
drwxr-xr-x 1 peter peter    512 Jan 10 19:42 .git
drwxr-xr-x 1 peter peter    512 Jan  6 10:16 .github
-rwxr--r-- 1 peter peter    211 Jan  6 10:16 .gitignore
-rwxr--r-- 1 peter peter   2892 Jan  6 10:16 LICENSE
drwxr-xr-x 1 peter peter    512 Jan  6 10:16 microservices
-rwxr--r-- 1 peter peter  10462 Jan  6 10:16 open-source-license-acknowledgements-and-third-party-copyrights.md
drwxr-xr-x 1 peter peter    512 Jan  6 10:16 packages
-rwxr--r-- 1 peter peter    210 Jan  6 10:16 parameters_monorepo.yml
-rwxr--r-- 1 peter peter    488 Jan  6 10:16 phing
-rwxr--r-- 1 peter peter     58 Jan  6 10:16 phing.bat
-rwxr--r-- 1 peter peter    328 Jan  6 10:16 phpstan.neon
drwxr-xr-x 1 peter peter    512 Jan  6 10:20 project-base
-rwxr--r-- 1 peter peter   5964 Jan 10 19:42 README.md
-rwxr--r-- 1 peter peter   5025 Jan  6 10:16 UPGRADE.md
```

**Comment by boris-brtan** [comment]
it is cloned OK, the problem will be with failed synchronization of docker-sync microservices volumes.
```
docker-compose down
docker-sync clean
docker-sync start
docker-compose up -d
```

**Comment by sspooky13** [comment]
I tried many times to clean everything up, but it's not worked. I try it now again but still not working 😞.
I copy here whole console output (i add empty line before every command for better read):

```bash
peter@Peter:/c/html/shopsys$ docker-compose down
Removing network shopsys_default
WARNING: Network shopsys_default not found.

peter@Peter:/c/html/shopsys$ docker-sync clean
    shutdown  Background sync has been stopped
sh: 1: brew: not found
CONTAINER ID        IMAGE                        COMMAND                  CREATED              STATUS              PORTS                       NAMES
7ee3c61abf4b        eugenmayer/unison:2.51.2.1   "/entrypoint.sh supe…"   About a minute ago   Up About a minute   127.0.0.1:32778->5000/tcp   shopsys-framework-vendor-sync
e010d2a29225        eugenmayer/unison:2.51.2.1   "/entrypoint.sh supe…"   About a minute ago   Up About a minute   127.0.0.1:32777->5000/tcp   shopsys-framework-web-sync
e8afbcd940b5        eugenmayer/unison:2.51.2.1   "/entrypoint.sh supe…"   About a minute ago   Up About a minute   127.0.0.1:32776->5000/tcp   shopsys-framework-microservice-product-search-export-sync
3ddfd01748b2        eugenmayer/unison:2.51.2.1   "/entrypoint.sh supe…"   2 minutes ago        Up 2 minutes        127.0.0.1:32775->5000/tcp   shopsys-framework-microservice-product-search-sync
5472df8e1a23        eugenmayer/unison:2.51.2.1   "/entrypoint.sh supe…"   2 minutes ago        Up 2 minutes        127.0.0.1:32774->5000/tcp   shopsys-framework-sync
     success  Finished cleanup. Removed stopped, removed sync container and removed their volumes

peter@Peter:/c/html/shopsys$ docker-sync start
          ok  Starting unison for sync shopsys-framework-sync
sh: 1: brew: not found
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
doing initial sync with unison
Unison 2.51.2 (ocaml 4.06.1): Contacting server...
Looking for changes
Reconciling changes
Propagating updates
UNISON 2.51.2 (OCAML 4.06.1) started propagating changes at 18:39:01.29 on 12 Jan 2019
[BGN] Copying  from /app_sync to /host_sync
[END] Copying
UNISON 2.51.2 (OCAML 4.06.1) finished propagating changes at 18:39:01.29 on 12 Jan 2019
Saving synchronizer state
Synchronization complete at 18:39:01  (1 item transferred, 0 skipped, 0 failed)
chown ing file to uid 1000
real    0m 0.06s
user    0m 0.03s
sys     0m 0.01s
          ok  Synced /c/html/shopsys/
     success  Unison server started
          ok  Starting unison for sync shopsys-framework-microservice-product-search-sync
doing initial sync with unison
Unison 2.51.2 (ocaml 4.06.1): Contacting server...
Looking for changes
Reconciling changes
Propagating updates
UNISON 2.51.2 (OCAML 4.06.1) started propagating changes at 18:39:12.00 on 12 Jan 2019
[BGN] Copying  from /app_sync to /host_sync
[END] Copying
UNISON 2.51.2 (OCAML 4.06.1) finished propagating changes at 18:39:12.00 on 12 Jan 2019
Saving synchronizer state
Synchronization complete at 18:39:12  (1 item transferred, 0 skipped, 0 failed)
real    0m 0.05s
user    0m 0.04s
sys     0m 0.00s
chown ing file to uid 1000
          ok  Synced /c/html/shopsys/microservices/product-search/
     success  Unison server started
          ok  Starting unison for sync shopsys-framework-microservice-product-search-export-sync
doing initial sync with unison
Unison 2.51.2 (ocaml 4.06.1): Contacting server...
Looking for changes
Reconciling changes
Propagating updates
UNISON 2.51.2 (OCAML 4.06.1) started propagating changes at 18:39:23.62 on 12 Jan 2019
[BGN] Copying  from /app_sync to /host_sync
[END] Copying
UNISON 2.51.2 (OCAML 4.06.1) finished propagating changes at 18:39:23.62 on 12 Jan 2019
Saving synchronizer state
Synchronization complete at 18:39:23  (1 item transferred, 0 skipped, 0 failed)
chown ing file to uid 1000
real    0m 0.06s
user    0m 0.04s
sys     0m 0.00s
          ok  Synced /c/html/shopsys/microservices/product-search-export/
     success  Unison server started
          ok  Starting unison for sync shopsys-framework-web-sync
doing initial sync with unison
Unison 2.51.2 (ocaml 4.06.1): Contacting server...
Looking for changes
Reconciling changes
Propagating updates
UNISON 2.51.2 (OCAML 4.06.1) started propagating changes at 18:39:42.52 on 12 Jan 2019
[BGN] Copying  from /app_sync to /host_sync
[END] Copying
UNISON 2.51.2 (OCAML 4.06.1) finished propagating changes at 18:39:42.52 on 12 Jan 2019
Saving synchronizer state
Synchronization complete at 18:39:42  (1 item transferred, 0 skipped, 0 failed)
chown ing file to uid 1000
real    0m 0.07s
user    0m 0.05s
sys     0m 0.00s
          ok  Synced /c/html/shopsys/project-base/web
     success  Unison server started
          ok  Starting unison for sync shopsys-framework-vendor-sync
doing initial sync with unison
Unison 2.51.2 (ocaml 4.06.1): Contacting server...
Looking for changes
Reconciling changes
Propagating updates
UNISON 2.51.2 (OCAML 4.06.1) started propagating changes at 18:39:51.77 on 12 Jan 2019
[BGN] Copying  from /app_sync to /host_sync
[END] Copying
UNISON 2.51.2 (OCAML 4.06.1) finished propagating changes at 18:39:51.77 on 12 Jan 2019
Saving synchronizer state
Synchronization complete at 18:39:51  (1 item transferred, 0 skipped, 0 failed)
real    0m 0.08s
user    0m 0.04s
sys     0m 0.00s
chown ing file to uid 1000
          ok  Synced /c/html/shopsys/vendor
     success  Unison server started
          ok  Synced /c/html/shopsys/
          ok  Synced /c/html/shopsys/microservices/product-search/
          ok  Synced /c/html/shopsys/microservices/product-search-export/
          ok  Synced /c/html/shopsys/project-base/web
          ok  Synced /c/html/shopsys/vendor
     success  Starting Docker-Sync in the background

peter@Peter:/c/html/shopsys$ docker-compose up -d
Creating network "shopsys_default" with the default driver
Creating shopsys-framework-redis                              ... done
Creating shopsys-framework-adminer                            ... done
Creating shopsys-framework-smtp-server                        ... done
Creating shopsys-framework-acceptance-tests                   ... done
Creating shopsys-framework-php-fpm                            ... done
Creating shopsys-framework-elasticsearch                      ... done
Creating shopsys-framework-microservice-product-search        ... done
Creating shopsys-framework-redis-admin                        ... done
Creating shopsys-framework-postgres                           ... done
Creating shopsys-framework-microservice-product-search-export ... done
Creating shopsys-framework-webserver                          ... done

peter@Peter:/c/html/shopsys$ docker-compose up -d
shopsys-framework-redis-admin is up-to-date
Starting shopsys-framework-microservice-product-search-export ...
shopsys-framework-adminer is up-to-date
shopsys-framework-smtp-server is up-to-date
shopsys-framework-acceptance-tests is up-to-date
Starting shopsys-framework-microservice-product-search        ...
shopsys-framework-php-fpm is up-to-date
shopsys-framework-postgres is up-to-date
shopsys-framework-redis is up-to-date
Starting shopsys-framework-microservice-product-search-export ... done
Starting shopsys-framework-microservice-product-search        ... done

peter@Peter:/c/html/shopsys$ docker logs shopsys-framework-microservice-product-search
standard_init_linux.go:190: exec user process caused "permission denied"
standard_init_linux.go:190: exec user process caused "permission denied"

peter@Peter:/c/html/shopsys$ docker logs shopsys-framework-microservice-product-search-export
standard_init_linux.go:190: exec user process caused "permission denied"
standard_init_linux.go:190: exec user process caused "permission denied"

peter@Peter:/c/html/shopsys$
```

**Comment by boris-brtan** [comment]
I will try to create travis testing script based on these info,In the meanwhile, if you do not want to do some changes into microservices you can modify your `docker-compose.yml` as it is for projectbase.
from
```yaml
    microservice-product-search:
        build:
            context: microservices/product-search
            dockerfile: docker/Dockerfile
            target: development
            args:
                <<: *common_build_args
        volumes:
            - ./microservices/product-search:/var/www/html

    microservice-product-search-export:
        build:
            context: microservices/product-search-export
            dockerfile: docker/Dockerfile
            target: development
            args:
                <<: *common_build_args
        volumes:
            - ./microservices/product-search-export:/var/www/html
```
to
```yaml
    microservice-product-search:
        image: shopsys/microservice-product-search:latest

    microservice-product-search-export:
        image: shopsys/microservice-product-search-export:latest
```
